### ISSUE TITLE
Featured images don't look good on mobile devices

### ISSUE THREAD

**Issue by bhavin192** [mebishalnapit/creative-blog#1]
As featured images are square, it doesn't look that much good as it looks on desktop layout. 
Can you provide option to disable them in mobile view (small width) 

btw 
really great theme 😉

**Comment by mebishalnapit** [comment]
Hi Bhavin Gandhi,

You can paste this CSS code in the Custom CSS Box provided through the Customizer Options through this theme and see if it works or not:

```
@media screen and (max-width: 480px) {
    .format-standard .featured-image {
        display: none;
    }
}
```

Remember to change the media query value here in the provided CSS code according to your site need.

Thanks.
Bishal Napit
